includeBuild("versionPlugin")
include(":app")
include(":function:main")
include(":function:home")
include(":function:listen")
include(":function:discover")
include(":function:mine")
include(":library:common")
include(":library:ximalaya")
include(":library:thirdpart")
include(":localRepo:ximalaya")
rootProject.name = "Ximalaya"